"""Data shapes shared between components.

The conversation itself (the `messages` list sent to the LLM) is deliberately kept as plain
dicts: that list IS the wire format of the Chat Completions API, and seeing it raw is the
point of this project. Pydantic is used at the boundaries where data needs validating or a
stable shape: LLM responses, tool results, sources, events, and the final result.
"""

from typing import Any, Literal

from pydantic import BaseModel, Field


# --- LLM -------------------------------------------------------------------------------

class ToolCall(BaseModel):
    """One tool request made by the LLM."""

    id: str          # Generated by the LLM API; the tool result must echo it back.
    name: str        # Which tool the model wants, e.g. "web_search".
    arguments: str   # A JSON *string* written by the model - not yet parsed or trusted.


class LLMResponse(BaseModel):
    """What the LLM returned for one call: either text, tool requests, or (rarely) both."""

    content: str | None = None
    tool_calls: list[ToolCall] = Field(default_factory=list)
    finish_reason: str | None = None
    usage: dict[str, Any] = Field(default_factory=dict)

    def to_message(self) -> dict[str, Any]:
        """Convert back into an assistant message for the conversation history.

        The API requires this message to be in the history *before* the tool results
        that answer it - otherwise the tool results have nothing to refer to.
        """
        message: dict[str, Any] = {"role": "assistant", "content": self.content}
        if self.tool_calls:
            message["tool_calls"] = [
                {
                    "id": call.id,
                    "type": "function",
                    "function": {"name": call.name, "arguments": call.arguments},
                }
                for call in self.tool_calls
            ]
        return message


# --- Tools -----------------------------------------------------------------------------

class SearchResult(BaseModel):
    """A single web search hit, independent of which search provider produced it."""

    title: str
    url: str
    snippet: str


class ToolResult(BaseModel):
    """What executing a tool produced.

    `data` is sent to the LLM as JSON. `sources` is kept separately so the orchestrator can
    number every URL and later verify citations - the LLM never gets to "own" the URLs.
    """

    ok: bool
    data: dict[str, Any] = Field(default_factory=dict)
    sources: list[SearchResult] = Field(default_factory=list)
    error: str | None = None


# --- Sources & final result ------------------------------------------------------------

class Source(SearchResult):
    """A search result that has been given a stable number the LLM can cite, e.g. [2]."""

    id: int


class AgentEvent(BaseModel):
    """Something observable the agent did. The UI decides how (or whether) to show it."""

    type: Literal[
        "user_question",
        "llm_request",
        "llm_response",
        "tool_call",
        "tool_result",
        "iteration_limit",
        "final_answer",
    ]
    data: dict[str, Any] = Field(default_factory=dict)


class AgentResult(BaseModel):
    """Everything the UI needs to present the final answer."""

    question: str
    answer: str
    cited_sources: list[Source] = Field(default_factory=list)
    retrieved_sources: list[Source] = Field(default_factory=list)
    tool_calls_made: int = 0
    iterations: int = 0
    stopped_reason: Literal["completed", "max_iterations"] = "completed"
    warnings: list[str] = Field(default_factory=list)

    @property
    def used_search(self) -> bool:
        return self.tool_calls_made > 0
